### ISSUE TITLE
"Internal Server Error" for recent query

### ISSUE THREAD

**Issue by Spencer-PW** [synfinner/KEVin#249]
```
https://kevin.gtfkd.com/kev/recent?days=7
```

I'm trying to access the API above, and got the following return:
```
{"message": "Internal Server Error"}
```

I checked the status page and it seems fine. May I know what's wrong here?

**Comment by synfinner** [comment]
This was due to some of our cache change over. I'm about to push a change that will fix this functionality shortly. Thank you for bringing this up!

**Comment by synfinner** [comment]
@Spencer-PW The functionality has been restored in prod. Thank you so much again for raising this issue! Closing this issue <3
